#!/bin/sh

### BEGIN INIT INFO
# Provides:        redis-what-the-role.rb
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start redis-what-the-role daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/opt/redis-what-the-role/

. /lib/lsb/init-functions

DAEMON=/opt/redis-what-the-role/redis-what-the-role.rb
PIDFILE=/var/run/redis-what-the-role.pid

test -x $DAEMON || exit 5

RUNASUSER=root

case $1 in
	start)
		log_daemon_msg "Starting redis-what-the-role server" "redis-what-the-role"
		if [ -z "$UGID" ]; then
			log_failure_msg "user \"$RUNASUSER\" does not exist"
			exit 1
		fi

  		start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE
		status=$?

		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping redis-what-the-role server" "redis-what-the-role"
  		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "redis-what-the-role server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
